<?php

namespace common\models\orm;

use Yii;

/**
 * This is the model class for table "xm_user".
 *
 * @property int $id id 
 * @property string $object_id 用户唯一标识
 * @property string $account 工号
 * @property string $nickname 姓名
 * @property string $password 密码 
 * @property string $phone 手机
 * @property string $email 邮箱
 * @property string $remark 描述
 * @property string $xmschool_id 小码校区，对应小码学校的id，0为集团，多个用,链接
 * @property int $create_time 录入时间
 * @property int $update_time 修改时间
 * @property int $status 状态：默认1，1为正常0为禁用可恢复，-1为删除
 * @property int $type_id 9为后台超级管理员
 * @property int $adder_id 添加人
 * @property int $sex 性别 1为男 2为女
 * @property string $birthday_time 出生日期
 * @property int $status_hunyin 婚姻状况 1为未婚 2为已婚 3为离婚
 * @property int $status_major 员工状态 1为正式 0为实习
 * @property string $bodynumber 身份正号码
 * @property string $school 毕业院校
 * @property string $major 专业
 * @property string $education 学历
 * @property string $end_year 毕业时间
 * @property string $qq QQ 
 * @property string $wechat 微信
 * @property string $jiguan 籍贯
 * @property string $jiguan_xingzhi 籍贯性质 1为本地非农村 -1为本地农村 2为外地非农村 -2为外地农村
 * @property string $ruzhi_time 入职时间
 * @property string $shengxiao_time 合同生效时间
 * @property string $jieshu_time 合同终止时间
 * @property string $zhuanzheng_time 转正时间
 * @property string $home_address 家庭住址
 * @property string $now_address 现居住地
 * @property int $main_contacts 紧急联系人 1为父亲 2为妈妈 3为配偶
 * @property string $father_phone 紧急联系人电话
 * @property int $computer 电脑状态1 为公司 0为个人
 * @property string $zhuangang_time 转岗日期
 * @property int $gongzuonianxian 工作年限
 * @property string $kahao 工资卡号
 * @property string $bank 开户银行
 * @property string $xiaoqu 所属校区
 * @property int $bumen 所属部门
 * @property int $zhiwei 所属职位
 * @property int $departure_time 离职时间
 */
class XmUser extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        $dbname = substr(static::getDb()->dsn, strpos(static::getDb()->dsn, "dbname=")+7);
        return $dbname.'.xm_user';
    }

    public static function getDb() {
        return Yii::$app->get('db2'); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id', 'create_time', 'update_time', 'adder_id', 'sex', 'status_hunyin', 'status_major', 'main_contacts', 'computer', 'gongzuonianxian', 'bumen', 'zhiwei', 'departure_time'], 'integer'],
            [['object_id', 'password', 'birthday_time', 'bodynumber', 'school', 'major', 'education', 'end_year', 'qq', 'wechat', 'jiguan', 'jiguan_xingzhi', 'ruzhi_time', 'shengxiao_time', 'jieshu_time', 'zhuanzheng_time', 'home_address', 'now_address', 'zhuangang_time', 'kahao', 'bank', 'xiaoqu'], 'string', 'max' => 32],
            [['account', 'nickname'], 'string', 'max' => 200],
            [['phone', 'father_phone'], 'string', 'max' => 13],
            [['email'], 'string', 'max' => 150],
            [['remark'], 'string', 'max' => 2000],
            [['xmschool_id'], 'string', 'max' => 800],
            [['status'], 'string', 'max' => 1],
            [['type_id'], 'string', 'max' => 2],
            [['account'], 'unique'],
            [['object_id'], 'unique'],
            [['id'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'object_id' => 'Object ID',
            'account' => 'Account',
            'nickname' => 'Nickname',
            'password' => 'Password',
            'phone' => 'Phone',
            'email' => 'Email',
            'remark' => 'Remark',
            'xmschool_id' => 'Xmschool ID',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'status' => 'Status',
            'type_id' => 'Type ID',
            'adder_id' => 'Adder ID',
            'sex' => 'Sex',
            'birthday_time' => 'Birthday Time',
            'status_hunyin' => 'Status Hunyin',
            'status_major' => 'Status Major',
            'bodynumber' => 'Bodynumber',
            'school' => 'School',
            'major' => 'Major',
            'education' => 'Education',
            'end_year' => 'End Year',
            'qq' => 'Qq',
            'wechat' => 'Wechat',
            'jiguan' => 'Jiguan',
            'jiguan_xingzhi' => 'Jiguan Xingzhi',
            'ruzhi_time' => 'Ruzhi Time',
            'shengxiao_time' => 'Shengxiao Time',
            'jieshu_time' => 'Jieshu Time',
            'zhuanzheng_time' => 'Zhuanzheng Time',
            'home_address' => 'Home Address',
            'now_address' => 'Now Address',
            'main_contacts' => 'Main Contacts',
            'father_phone' => 'Father Phone',
            'computer' => 'Computer',
            'zhuangang_time' => 'Zhuangang Time',
            'gongzuonianxian' => 'Gongzuonianxian',
            'kahao' => 'Kahao',
            'bank' => 'Bank',
            'xiaoqu' => 'Xiaoqu',
            'bumen' => 'Bumen',
            'zhiwei' => 'Zhiwei',
            'departure_time' => 'Departure Time',
        ];
    }
}
